# .github/workflows/auto-merge-master-to-main.yml

name: Auto Merge master -> main (no conflicts)

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch and merge master (check conflicts)
        run: |
          git fetch origin master:master-temp

          # Try to merge without committing
          git merge --no-commit --no-ff master-temp || {
            echo "❌ Merge conflict! Not merging.";
            exit 1;
          }

      - name: Commit and push merged changes (if merge successful)
        run: |
          git commit -m "✅ Auto-merged changes from master to main"
          git push origin main
