# .github/workflows/auto-merge-master-to-main.yml

name: Auto Merge master -> main (no conflicts)

on:
  push:
    branches:
      - master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure Git
        run: |
          git config user.name "manishkr108"
          git config user.email "manishkr108@users.noreply.github.com"

      - name: Fetch and try to merge master (no conflicts only)
        run: |
          git fetch origin master:master-temp

          # Try merge with unrelated histories allowed
          git merge --allow-unrelated-histories --no-commit --no-ff master-temp || {
            echo "❌ Merge conflict or unrelated history merge failed. Skipping.";
            exit 1;
          }

      - name: Commit and push merged changes (if successful)
        run: |
          git commit -m "✅ Auto-merged changes from master to main"
          git push origin main
